### ISSUE TITLE
Extended Macros Not Working in 10.0.2

### ISSUE THREAD

**Issue by Xatops** [Numynum/MacroToolkit#10]
As of phase 2 prepatch extended macros aren't working for me. Tried copying the text and creating a new extended macro (worked previously) but no dice this time.

See below (Pressing the button does nothing)

#showtooltip [stealth,mod]Cheap Shot;[stealth]Shadowstrike;[nocombat]Stealth;[mod]Eviscerate;Backstab
/cleartarget [dead]
/targetenemy [noharm]
/castsequence [nostealth,nocombat]Stealth;[nomod]reset=0.40 Backstab,0
/castsequence [mod]Eviscerate;Flagellation
/castsequence [mod]reset=3 Eviscerate,Shadow Dance

**Comment by Gaviin1242** [comment]
Same issue here.  No lua errors or anything, but extended macros don't do anything.  And just to be clear, this is in v10.0.2 of the game.

**Comment by Numynum** [comment]
blizzard made some changes again to how the magic behind extended macros works
I'll look into what's needed to change this time

**Comment by Numynum** [comment]
should be fixed in next update
it's hard to tell if there's any bad side effects though :/

**Comment by chodyo** [comment]
I'm on the latest version but I'm still unable to use extended macros.

**Comment by Numynum** [comment]
@chodyo create a new issue, with more info (example macro that doesn't work; what's broken about it; if you tried with 0 other addons enabled; etc)
